language: python
python: 2.7

cache:
  directories:
    - $HOME/.cache/pip

env:
  global:
    - DATABASE_URL="mysql://root:@localhost/test_feder"
    - DJANGO_CONFIGURATION="Local"
  matrix:
    - TOX_ENV=coverage-py27-dj17
    - TOX_ENV=flake8
    - TOX_ENV=py27-dj18
    - TOX_ENV=py27-djmaster
    - TOX_ENV=py33-dj18
    - TOX_ENV=py33-djmaster

matrix:
  allow_failures:
    - env: TOX_ENV=flake8
    - env: TOX_ENV=py27-djmaster
    - env: TOX_ENV=py33-dj18
    - env: TOX_ENV=py33-djmaster


install:
  - pip install -U pip wheel
  - pip install tox
script:
  - tox -e $TOX_ENV

notifications:
  slack: watchdogpolska:mQq180xGu9UcuJgK73hVWECD

after_script:
- rm $HOME/.cache/pip/log/*

